In [74]:
import numpy as np
import pandas as pd

In [75]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data",names=["symboling", "normalized_losses",
"make", "fuel_type", "aspiration","num_doors", "body_style", "drive_wheels",
"engine_location", "wheel_base", "length", "width", "height", "curb_weight",
"engine_type", "num_cylinders", "engine_size", "fuel_system", "bore", "stroke",
"compression_ratio", "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price"],na_values='?')
df

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [76]:
df.dropna(subset=['price'],inplace=True)
df.reset_index(drop=True,inplace=True)
df

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
197,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
198,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
199,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
200,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [77]:
df.dtypes

symboling              int64
normalized_losses    float64
make                  object
fuel_type             object
aspiration            object
num_doors             object
body_style            object
drive_wheels          object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_cylinders         object
engine_size            int64
fuel_system           object
bore                 float64
stroke               float64
compression_ratio    float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                float64
dtype: object

In [78]:
df.dtypes.index

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'num_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'num_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [79]:
keys=list(df.dtypes.index[df.dtypes!=object])
for key in keys:
    df[key].fillna(df[key].mean(),inplace=True)
df

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
197,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
198,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
199,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
200,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [80]:
keys_category=list(df.dtypes.index[df.dtypes==object])
for key in keys_category:
    df[key].fillna(df[key].mode()[0],inplace=True)
df

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
197,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
198,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
199,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
200,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [81]:
from sklearn.ensemble import IsolationForest
iso_forest=IsolationForest()

In [82]:
iso_forest.fit(df[['length']])
predicted=iso_forest.predict(df[['length']])
ind_of_outliers=np.where(predicted==-1)
ind_of_outliers

(array([  6,   7,   8,  15,  16,  17,  18,  19,  29,  30,  31,  32,  33,
         34,  35,  44,  45,  46,  47,  48,  49,  64,  65,  66,  67,  68,
         69,  70,  71,  72,  95,  98,  99, 100, 103, 106, 107, 110, 111,
        126, 134, 135, 146, 147, 148, 174, 175, 185, 187, 188, 189],
       dtype=int64),)

In [83]:
outliers=df['length'].iloc[ind_of_outliers]
outliers

6      192.7
7      192.7
8      192.7
15     193.8
16     197.0
17     141.1
18     155.9
19     158.8
29     144.6
30     144.6
31     150.0
32     150.0
33     150.0
34     163.4
35     157.1
44     199.6
45     199.6
46     191.7
47     159.1
48     159.1
49     159.1
64     190.9
65     190.9
66     187.5
67     202.6
68     202.6
69     180.3
70     208.1
71     199.2
72     178.4
95     162.4
98     181.7
99     184.6
100    184.6
103    178.5
106    198.9
107    198.9
110    198.9
111    198.9
126    181.5
134    156.9
135    157.9
146    158.7
147    158.7
148    158.7
174    183.5
175    183.5
185    159.3
187    180.2
188    180.2
189    183.1
Name: length, dtype: float64

In [84]:
df['num_doors'].unique()

array(['two', 'four'], dtype=object)

In [85]:
df['num_cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [86]:
dictionary={'two':2,'three':3,'four':4,'six':6,'five':5,'twelve':12,'eight':8}

In [87]:
for key in dictionary.keys():
    df[['num_doors','num_cylinders']]=df[['num_doors','num_cylinders']].replace(key,dictionary[key])

In [88]:
df

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,122.0,alfa-romero,gas,std,2,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,122.0,alfa-romero,gas,std,2,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,122.0,alfa-romero,gas,std,2,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,4,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,4,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95.0,volvo,gas,std,4,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
197,-1,95.0,volvo,gas,turbo,4,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
198,-1,95.0,volvo,gas,std,4,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
199,-1,95.0,volvo,diesel,turbo,4,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
200,-1,95.0,volvo,gas,turbo,4,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [89]:
dummies=pd.get_dummies(df[["body_style", "drive_wheels"]])
df=pd.concat((df,dummies),axis=1)
df.drop(columns=["body_style", "drive_wheels"],inplace=True)
df

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,engine_location,wheel_base,length,width,...,highway_mpg,price,body_style_convertible,body_style_hardtop,body_style_hatchback,body_style_sedan,body_style_wagon,drive_wheels_4wd,drive_wheels_fwd,drive_wheels_rwd
0,3,122.0,alfa-romero,gas,std,2,front,88.6,168.8,64.1,...,27,13495.0,1,0,0,0,0,0,0,1
1,3,122.0,alfa-romero,gas,std,2,front,88.6,168.8,64.1,...,27,16500.0,1,0,0,0,0,0,0,1
2,1,122.0,alfa-romero,gas,std,2,front,94.5,171.2,65.5,...,26,16500.0,0,0,1,0,0,0,0,1
3,2,164.0,audi,gas,std,4,front,99.8,176.6,66.2,...,30,13950.0,0,0,0,1,0,0,1,0
4,2,164.0,audi,gas,std,4,front,99.4,176.6,66.4,...,22,17450.0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95.0,volvo,gas,std,4,front,109.1,188.8,68.9,...,28,16845.0,0,0,0,1,0,0,0,1
197,-1,95.0,volvo,gas,turbo,4,front,109.1,188.8,68.8,...,25,19045.0,0,0,0,1,0,0,0,1
198,-1,95.0,volvo,gas,std,4,front,109.1,188.8,68.9,...,23,21485.0,0,0,0,1,0,0,0,1
199,-1,95.0,volvo,diesel,turbo,4,front,109.1,188.8,68.9,...,27,22470.0,0,0,0,1,0,0,0,1
200,-1,95.0,volvo,gas,turbo,4,front,109.1,188.8,68.9,...,25,22625.0,0,0,0,1,0,0,0,1

In [90]:
from sklearn.preprocessing import LabelEncoder
label_enc=LabelEncoder()
features=['make', 'aspiration', 'engine_location','fuel_type']
for feature in features:
    df[feature]=label_enc.fit_transform(df[feature])
df

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,engine_location,wheel_base,length,width,...,highway_mpg,price,body_style_convertible,body_style_hardtop,body_style_hatchback,body_style_sedan,body_style_wagon,drive_wheels_4wd,drive_wheels_fwd,drive_wheels_rwd
0,3,122.0,0,1,0,2,0,88.6,168.8,64.1,...,27,13495.0,1,0,0,0,0,0,0,1
1,3,122.0,0,1,0,2,0,88.6,168.8,64.1,...,27,16500.0,1,0,0,0,0,0,0,1
2,1,122.0,0,1,0,2,0,94.5,171.2,65.5,...,26,16500.0,0,0,1,0,0,0,0,1
3,2,164.0,1,1,0,4,0,99.8,176.6,66.2,...,30,13950.0,0,0,0,1,0,0,1,0
4,2,164.0,1,1,0,4,0,99.4,176.6,66.4,...,22,17450.0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95.0,21,1,0,4,0,109.1,188.8,68.9,...,28,16845.0,0,0,0,1,0,0,0,1
197,-1,95.0,21,1,1,4,0,109.1,188.8,68.8,...,25,19045.0,0,0,0,1,0,0,0,1
198,-1,95.0,21,1,0,4,0,109.1,188.8,68.9,...,23,21485.0,0,0,0,1,0,0,0,1
199,-1,95.0,21,0,1,4,0,109.1,188.8,68.9,...,27,22470.0,0,0,0,1,0,0,0,1
200,-1,95.0,21,1,1,4,0,109.1,188.8,68.9,...,25,22625.0,0,0,0,1,0,0,0,1

In [91]:
arr = []
for val in df['fuel_system']:
    if 'pfi' in val:
        arr.append(1)
    else:
        arr.append(0)
df['fuel_system'] = arr
df['fuel_system']

0      1
1      1
2      1
3      1
4      1
      ..
196    1
197    1
198    1
199    0
200    1
Name: fuel_system, Length: 201, dtype: int64

In [92]:
arr1=[]
for val in df['engine_type']:
    if 'ohc' in val:
        arr1.append(1)
    else:
        arr1.append(0)
df['engine_type'] = arr1
df['engine_type']

0      1
1      1
2      1
3      1
4      1
      ..
196    1
197    1
198    1
199    1
200    1
Name: engine_type, Length: 201, dtype: int64

In [93]:
input_features=df.iloc[:,:-1]
output_features=df.iloc[:,-1]
input_features

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,engine_location,wheel_base,length,width,...,city_mpg,highway_mpg,price,body_style_convertible,body_style_hardtop,body_style_hatchback,body_style_sedan,body_style_wagon,drive_wheels_4wd,drive_wheels_fwd
0,3,122.0,0,1,0,2,0,88.6,168.8,64.1,...,21,27,13495.0,1,0,0,0,0,0,0
1,3,122.0,0,1,0,2,0,88.6,168.8,64.1,...,21,27,16500.0,1,0,0,0,0,0,0
2,1,122.0,0,1,0,2,0,94.5,171.2,65.5,...,19,26,16500.0,0,0,1,0,0,0,0
3,2,164.0,1,1,0,4,0,99.8,176.6,66.2,...,24,30,13950.0,0,0,0,1,0,0,1
4,2,164.0,1,1,0,4,0,99.4,176.6,66.4,...,18,22,17450.0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95.0,21,1,0,4,0,109.1,188.8,68.9,...,23,28,16845.0,0,0,0,1,0,0,0
197,-1,95.0,21,1,1,4,0,109.1,188.8,68.8,...,19,25,19045.0,0,0,0,1,0,0,0
198,-1,95.0,21,1,0,4,0,109.1,188.8,68.9,...,18,23,21485.0,0,0,0,1,0,0,0
199,-1,95.0,21,0,1,4,0,109.1,188.8,68.9,...,26,27,22470.0,0,0,0,1,0,0,0
200,-1,95.0,21,1,1,4,0,109.1,188.8,68.9,...,19,25,22625.0,0,0,0,1,0,0,0

In [94]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
scaled_input_features=pd.DataFrame(ss.fit_transform(input_features),columns=input_features.keys())
scaled_input_features

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,engine_location,wheel_base,length,width,...,city_mpg,highway_mpg,price,body_style_convertible,body_style_hardtop,body_style_hatchback,body_style_sedan,body_style_wagon,drive_wheels_4wd,drive_wheels_fwd
0,1.725050,0.000000,-1.971717,0.332411,-0.467099,-1.156378,-0.123091,-1.685107,-0.439409,-0.853460,...,-0.652249,-0.542288,0.036314,5.700877,-0.203595,-0.715037,-0.937286,-0.376889,-0.203595,-1.192345
1,1.725050,0.000000,-1.971717,0.332411,-0.467099,-1.156378,-0.123091,-1.685107,-0.439409,-0.853460,...,-0.652249,-0.542288,0.415385,5.700877,-0.203595,-0.715037,-0.937286,-0.376889,-0.203595,-1.192345
2,0.127193,0.000000,-1.971717,0.332411,-0.467099,-1.156378,-0.123091,-0.710103,-0.244152,-0.185597,...,-0.964397,-0.689386,0.415385,-0.175412,-0.203595,1.398529,-0.937286,-0.376889,-0.203595,-1.192345
3,0.926121,1.315931,-1.811395,0.332411,-0.467099,0.864769,-0.123091,0.165748,0.195176,0.148335,...,-0.184027,-0.100993,0.093711,-0.175412,-0.203595,-0.715037,1.066910,-0.376889,-0.203595,0.838683
4,0.926121,1.315931,-1.811395,0.332411,-0.467099,0.864769,-0.123091,0.099646,0.195176,0.243744,...,-1.120471,-1.277779,0.535224,-0.175412,-0.203595,-0.715037,1.066910,-0.376889,4.911721,-1.192345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1.470664,-0.845956,1.395038,0.332411,-0.467099,0.864769,-0.123091,1.702619,1.187733,1.436357,...,-0.340101,-0.395189,0.458906,-0.175412,-0.203595,-0.715037,1.066910,-0.376889,-0.203595,-1.192345
197,-1.470664,-0.845956,1.395038,0.332411,2.140872,0.864769,-0.123091,1.702619,1.187733,1.388653,...,-0.964397,-0.836484,0.736429,-0.175412,-0.203595,-0.715037,1.066910,-0.376889,-0.203595,-1.192345
198,-1.470664,-0.845956,1.395038,0.332411,-0.467099,0.864769,-0.123091,1.702619,1.187733,1.436357,...,-1.120471,-1.130681,1.044227,-0.175412,-0.203595,-0.715037,1.066910,-0.376889,-0.203595,-1.192345
199,-1.470664,-0.845956,1.395038,-3.008322,2.140872,0.864769,-0.123091,1.702619,1.187733,1.436357,...,0.128120,-0.542288,1.168481,-0.175412,-0.203595,-0.715037,1.066910,-0.376889,-0.203595,-1.192345
200,-1.470664,-0.845956,1.395038,0.332411,2.140872,0.864769,-0.123091,1.702619,1.187733,1.436357,...,-0.964397,-0.836484,1.188034,-0.175412,-0.203595,-0.715037,1.066910,-0.376889,-0.203595,-1.192345